name: python-microscopy
channels:
  - conda-forge
  - bioconda
  - anaconda
dependencies:
  - anaconda::ipykernel=5.1.4
  - conda-forge::numpy=1.18.1
  - conda-forge::pandas=1.0.3
  - conda-forge::matplotlib=3.2.1
  - conda-forge::matplotlib-venn=0.11
  - conda-forge::h5py=2.10.0
  - bioconda::scanpy=1.4.4.post1
  - anaconda::scikit-image=0.16.2
  - conda-forge::scikit-learn=0.22.2
  - conda-forge::opencv=4.2.0
